00_youtube_download_descriptions: "/home/guilherme/Desktop/dissertation/data/download_descriptions.csv"
00_inputation_schema: "/home/guilherme/Desktop/dissertation/data/inputation_schema.csv"
00_bad_words: "/home/guilherme/Desktop/dissertation/data/noswearing.csv"
00_bad_words_scored: "/home/guilherme/Desktop/dissertation/data/noswearing_scored.csv"

01_youtube_raw: "/home/guilherme/Desktop/dissertation/data/01_raw/youtube/"
01_coraal_raw: "/home/guilherme/Desktop/dissertation/data/01_raw/coraal/"
01_buckeye_raw: "/home/guilherme/Desktop/dissertation/data/01_raw/buckeye/"

02_youtube_preprocessed: "/home/guilherme/Desktop/dissertation/data/02_preprocessed/youtube/"
02_coraal_preprocessed: "/home/guilherme/Desktop/dissertation/data/02_preprocessed/coraal/"
02_buckeye_preprocessed: "/home/guilherme/Desktop/dissertation/data/02_preprocessed/buckeye/"

03_youtube_segmented: "/home/guilherme/Desktop/dissertation/data/03_segmented/youtube/"
03_coraal_segmented: "/home/guilherme/Desktop/dissertation/data/03_segmented/coraal/"
03_buckeye_segmented: "/home/guilherme/Desktop/dissertation/data/03_segmented/buckeye/"

04_youtube_scored: "/home/guilherme/Desktop/dissertation/data/04_scored/youtube/"
04_coraal_scored: "/home/guilherme/Desktop/dissertation/data/04_scored/coraal/"
04_buckeye_scored: "/home/guilherme/Desktop/dissertation/data/04_scored/buckeye/"

imgs: "/home/guilherme/Desktop/dissertation/data/imgs/"