00_youtube_data_description: "/home/luiznery/locus/dissertation/data/youtube_data_description.csv"
00_buckeye_data_description: "/home/luiznery/locus/dissertation/data/buckeye_data_description.csv"
00_inputation_schema: "/home/luiznery/locus/dissertation/data/inputation_schema.csv"
00_bad_words: "/home/luiznery/locus/dissertation/data/noswearing.csv"
00_bad_words_scored: "/home/luiznery/locus/dissertation/data/noswearing_scored.csv"

01_youtube_raw: "/home/luiznery/locus/dissertation/data/01_raw/youtube/"
01_coraal_raw: "/home/luiznery/locus/dissertation/data/01_raw/coraal/"
01_buckeye_raw: "/home/luiznery/locus/dissertation/data/01_raw/buckeye/"
01_twitter_raw: "/home/luiznery/locus/dissertation/data/01_raw/twitter/"

02_youtube_preprocessed: "/home/luiznery/locus/dissertation/data/02_preprocessed/youtube/"
02_coraal_preprocessed: "/home/luiznery/locus/dissertation/data/02_preprocessed/coraal/"
02_buckeye_preprocessed: "/home/luiznery/locus/dissertation/data/02_preprocessed/buckeye/"
02_twitter_preprocessed: "/home/luiznery/locus/dissertation/data/02_preprocessed/twitter/"

03_youtube_segmented: "/home/luiznery/locus/dissertation/data/03_segmented/youtube/"
03_coraal_segmented: "/home/luiznery/locus/dissertation/data/03_segmented/coraal/"
03_buckeye_segmented: "/home/luiznery/locus/dissertation/data/03_segmented/buckeye/"
03_twitter_segmented: "/home/luiznery/locus/dissertation/data/03_segmented/twitter/"

04_youtube_scored: "/home/luiznery/locus/dissertation/data/04_scored/youtube/"
04_coraal_scored: "/home/luiznery/locus/dissertation/data/04_scored/coraal/"
04_buckeye_scored: "/home/luiznery/locus/dissertation/data/04_scored/buckeye/"
04_twitter_scored: "/home/luiznery/locus/dissertation/data/04_scored/twitter/"
04_interview_scored: "/home/luiznery/locus/dissertation/data/04_scored/interview/"

05_youtube_features: "/home/luiznery/locus/dissertation/data/05_regression_variables/buckeye_vs_coraal/youtube_features.csv"
05_buckeye_corall_features: "/home/luiznery/locus/dissertation/data/05_regression_variables/buckeye_vs_coraal/buckeye_vs_coraal_features.csv"
05_twitter_features: "/home/luiznery/locus/dissertation/data/05_regression_variables/buckeye_vs_coraaltwitter_features.csv"

youtube_imgs: "/home/luiznery/locus/dissertation/data/imgs/youtube"
buckeye_vs_coraal_imgs: "/home/luiznery/locus/dissertation/data/imgs/coraal"
twitter_imgs: "/home/luiznery/locus/dissertation/data/imgs/twitter"
imgs: "/home/luiznery/locus/dissertation/data/imgs/"

youtube_data_description: "/home/luiznery/locus/dissertation/data/youtube_data_description.csv"
buckeye_data_description: "/home/luiznery/locus/dissertation/data/buckeye_data_description.csv"
liwc_dict: "/home/luiznery/locus/dissertation/data/LIWC2015_English_Flat.dic"

utils: "/home/luiznery/locus/dissertation/utils/"