download_descriptions: "/home/guilherme/Desktop/dissertation/data/download_descriptions.csv"
bad_words_raw: "/home/guilherme/Desktop/dissertation/data/bad_words.txt"
bad_words_scored: "/home/guilherme/Desktop/dissertation/data/bad_words_scored.json"

raw_data: "/home/guilherme/Desktop/dissertation/data/00_raw/"
preprocessed_data: "/home/guilherme/Desktop/dissertation/data/01_preprocessed/without_inputation/"
fixed_size_segmentated_data: "/home/guilherme/Desktop/dissertation/data/02_segmented/fixed_size_context/without_curse_words/"
model_based_segmentated_data: "/home/guilherme/Desktop/dissertation/data/02_segmented/model_based/without_curse_words/"
perspective_scored_data: "/home/guilherme/Desktop/dissertation/data/03_scored/without_inputation/normal_toxicity/perspective"
textblob_scored_data: "/home/guilherme/Desktop/dissertation/data/03_scored/without_inputation/normal_toxicity/textblob"
vader_scored_data: "/home/guilherme/Desktop/dissertation/data/03_scored/without_inputation/normal_toxicity/vader"
flair_scored_data: "/home/guilherme/Desktop/dissertation/data/03_scored/without_inputation/normal_toxicity/flair"
imgs: "/home/guilherme/Desktop/dissertation/data/imgs/"

fine_tunning_raw_data: "/home/guilherme/Desktop/dissertation/data/TED_Talks/01_raw/subtitles.json"
fine_tunning_preprocessed: "/home/guilherme/Desktop/dissertation/data/TED_Talks/02_preprocessed/"
