base_path: "/home/guilherme/Desktop"

00_youtube_data_description: "dissertation/data/youtube_data_description.csv"
00_buckeye_data_description: "dissertation/data/buckeye_data_description.csv"
00_inputation_schema: "dissertation/data/inputation_schema.csv"
00_bad_words: "dissertation/data/noswearing.csv"
00_bad_words_score: "dissertation/data/noswearing_scored.csv"
00_liwc_dict: "dissertation/data/LIWC2015_English_Flat.dic"
00_aae_terms: "dissertation/data/aae_terms_black_talk.yaml"
00_cols_to_remove: "dissertation/data/cols_to_remove.yaml"

01_youtube_raw: "dissertation/data/01_raw/youtube/"
01_coraal_raw: "dissertation/data/01_raw/coraal/"
01_buckeye_raw: "dissertation/data/01_raw/buckeye/"
01_twitter_raw: "dissertation/data/01_raw/twitter/"

02_youtube_preprocessed: "dissertation/data/02_preprocessed/youtube/"
02_coraal_preprocessed: "dissertation/data/02_preprocessed/coraal/"
02_buckeye_preprocessed: "dissertation/data/02_preprocessed/buckeye/"
02_twitter_preprocessed: "dissertation/data/02_preprocessed/twitter/"

03_youtube_segmented: "dissertation/data/03_segmented/youtube/"
03_coraal_segmented: "dissertation/data/03_segmented/coraal/"
03_buckeye_segmented: "dissertation/data/03_segmented/buckeye/"
03_twitter_segmented: "dissertation/data/03_segmented/twitter/"

04_youtube_scored: "dissertation/data/04_scored/youtube/"
04_coraal_scored: "dissertation/data/04_scored/coraal/"
04_buckeye_scored: "dissertation/data/04_scored/buckeye/"
04_twitter_scored: "dissertation/data/04_scored/twitter/"

05_youtube_features: "dissertation/data/05_features/youtube/"
05_coraal_features: "dissertation/data/05_features/coraal/"
05_buckeye_features: "dissertation/data/05_features/buckeye/"
05_twitter_features: "dissertation/data/05_features/twitter/"

06_youtube_regression: "dissertation/data/06_regression_outputs/youtube/"
06_coraal_vs_buckeye_regression: "dissertation/data/06_regression_outputs/coraal_vs_buckeye/"
06_twitter_regression: "dissertation/data/06_regression_outputs/twitter/"

07_word_mover_distance: "dissertation/data/07_word_mover_distance/"

youtube_imgs: "dissertation/data/imgs/youtube"
buckeye_vs_coraal_imgs: "dissertation/data/imgs/buckeye_vs_coraal"
twitter_imgs: "dissertation/data/imgs/twitter"
