00_youtube_data_description: "/home/guilherme/Desktop/dissertation/data/youtube_data_description.csv"
00_buckeye_data_description: "/home/guilherme/Desktop/dissertation/data/buckeye_data_description.csv"
00_inputation_schema: "/home/guilherme/Desktop/dissertation/data/inputation_schema.csv"
00_bad_words: "/home/guilherme/Desktop/dissertation/data/noswearing.csv"

01_youtube_raw: "/home/guilherme/Desktop/dissertation/data/01_raw/youtube/"
01_coraal_raw: "/home/guilherme/Desktop/dissertation/data/01_raw/coraal/"
01_buckeye_raw: "/home/guilherme/Desktop/dissertation/data/01_raw/buckeye/"
01_twitter_raw: "/home/guilherme/Desktop/dissertation/data/01_raw/twitter/"

02_youtube_preprocessed: "/home/guilherme/Desktop/dissertation/data/02_preprocessed/youtube/"
02_coraal_preprocessed: "/home/guilherme/Desktop/dissertation/data/02_preprocessed/coraal/"
02_buckeye_preprocessed: "/home/guilherme/Desktop/dissertation/data/02_preprocessed/buckeye/"
02_twitter_preprocessed: "/home/guilherme/Desktop/dissertation/data/02_preprocessed/twitter/"

03_youtube_segmented: "/home/guilherme/Desktop/dissertation/data/03_segmented/youtube/"
03_coraal_segmented: "/home/guilherme/Desktop/dissertation/data/03_segmented/coraal/"
03_buckeye_segmented: "/home/guilherme/Desktop/dissertation/data/03_segmented/buckeye/"
03_twitter_segmented: "/home/guilherme/Desktop/dissertation/data/03_segmented/twitter/"

04_youtube_scored: "/home/guilherme/Desktop/dissertation/data/04_scored/youtube/"
04_coraal_scored: "/home/guilherme/Desktop/dissertation/data/04_scored/coraal/"
04_buckeye_scored: "/home/guilherme/Desktop/dissertation/data/04_scored/buckeye/"
04_twitter_scored: "/home/guilherme/Desktop/dissertation/data/04_scored/twitter/"

05_youtube_features: "dissertation/data/05_features/youtube/"
05_coraal_features: "dissertation/data/05_features/coraal/"
05_buckeye_features: "dissertation/data/05_features/buckeye/"
05_twitter_features: "dissertation/data/05_features/twitter/"

youtube_imgs: "/home/guilherme/Desktop/dissertation/data/imgs/youtube"
buckeye_vs_coraal_imgs: "/home/guilherme/Desktop/dissertation/data/imgs/buckeye_vs_coraal"
twitter_imgs: "/home/guilherme/Desktop/dissertation/data/imgs/twitter"