00_youtube_download_descriptions: "/home/guilherme/Desktop/dissertation/data/download_descriptions.csv"
00_inputation_schema: "/home/guilherme/Desktop/dissertation/data/inputation_schema.csv"
00_bad_words: "/home/guilherme/Desktop/dissertation/data/noswearing.csv"
00_bad_words_scored: "/home/guilherme/Desktop/dissertation/data/noswearing_scored.csv"

01_youtube_raw: "/home/guilherme/Desktop/dissertation/data/01_raw/youtube/"

02_youtube_preprocessed: "/home/guilherme/Desktop/dissertation/data/02_preprocessed/youtube/"

03_youtube_segmented: "/home/guilherme/Desktop/dissertation/data/03_segmented/youtube/"

04_youtube_scored: "/home/guilherme/Desktop/dissertation/data/04_scored/youtube/"

imgs: "/home/guilherme/Desktop/dissertation/data/imgs/"